name: Generating readme file
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name : Running Writereadme.py file
        run: python Writereadme.py
  push:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: build
      uses: github-actions-x/hugo@master
    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.ACCESS_KEY }}
        push-branch: 'master'
        commit-message: 'publish'
        force-add: 'true'
        files: .
        name: Naveenkumar M
        email: naveen9715568487@email.com

          






          