name: Generating readme file
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name : Running Writereadme.py file
        run: python Writereadme.py
      - name : Generating new version
        with:
          token : ${{secrets.ACCESS_KEY}}
        run: |
          git config user.name "Naveenkumar M"
          git config user.email naveen9715568487@gmail.com
          git add .
          git commit -m "generating reafctored files"
          git push origin master





          